# Generated by Django 5.0.6 on 2024-05-30 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mi_aplicacion', '0003_remove_refugio_mascota_id_refugio_mascota_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoptante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mi_aplicacion.mascota')),
                ('adoptante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopcion.adoptante')),
            ],
            options={
                'ordering': ('-fecha_adopcion',),
            },
        ),
    ]
