# Generated by Django 5.0.6 on 2024-05-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='mascota_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_aplicacion.mascota'),
        ),
    ]
