# Generated by Django 5.0.6 on 2024-05-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_refugio_mascota_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refugio',
            name='mascota_id',
        ),
        migrations.AddField(
            model_name='refugio',
            name='mascota_id',
            field=models.ManyToManyField(blank=True, related_name='refugios', to='mi_aplicacion.mascota'),
        ),
    ]
