# Generated by Django 5.0.6 on 2024-05-30 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_remove_refugio_mascota_id_refugio_mascota_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='refugio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='mi_aplicacion.refugio'),
        ),
        migrations.AddField(
            model_name='refugio',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
