# Generated by Django 5.0.6 on 2024-05-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_remove_refugio_mascota_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adoptante',
        ),
    ]
